# Very basic Travis CI (http://travis-ci.org) control file that allows
# some basic Linux-based continuous integration testing (for free).

sudo: required
dist: trusty

language: c

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "BIl7HDdWo2EpK63Nta2Sjy/V2rMYt4E5Jl+tWEkWR3be+s61oRg2DoIqdTTntvo8os8gq90Fb8WJJWZQ2806BfsNF+Z+DZqN59iNQOEB2aiA0BhggyOHnF+OoZZfgv7q4Eq0XOS7KLSrnCu18E0qQKxJSjnBrO9k1cLS3QnKDCA="

# Before setting up the source tree, install necessary development
# headers
before_install: >
  sudo apt-get update && 
  sudo apt-get install -y \
    libgtk2.0-dev autopoint libgettextpo-dev libstroke0-dev \
    guile-2.0-dev flex bison groff \
    texinfo texlive-base texlive-generic-recommended texlive-latex-base

# Set up the source tree by running autotools
install: ./autogen.sh && ./configure --disable-update-xdg-database

# Compile gEDA and run its tests
script: >
  if test "${COVERITY_SCAN_BRANCH}" != "1"; then
    make -kj4 distcheck
  fi

addons:
  # In order to trigger static analysis with Coverity Scan, push to
  # the coverity_scan branch.  You should only usually scan the tip of
  # "master-ng".
  coverity_scan:
    project:
      name: peter-b/geda-gaf
      description: Build submitted via Travis CI
    notification_email: peter@peter-b.co.uk
    build_command: make all
    branch_pattern: coverity_scan
